# Generated by Django 3.1.7 on 2021-03-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RickrollPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(help_text='Write a catchy description for your fake post.', max_length=250, verbose_name='Description')),
                ('slug', models.CharField(max_length=50, unique_for_date=True, verbose_name='Slug')),
                ('image', models.URLField(blank=True, help_text='You can provide an image for extra trickery.', verbose_name='Image URL')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Rickroll Post',
                'verbose_name_plural': 'Rickroll Posts',
            },
        ),
        migrations.AddIndex(
            model_name='rickrollpost',
            index=models.Index(fields=['date', 'slug'], name='rickroller__date_349ce3_idx'),
        ),
    ]
