# Generated by Django 3.1.7 on 2021-04-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rickroller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rickrollpost',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='Redirect URL. Defaults to Rick Astley\'s "Never Gonna Give You Up" offical VEVO video on YouTube.', max_length=512, null=True, verbose_name='Redirect URL'),
        ),
        migrations.AlterField(
            model_name='rickrollpost',
            name='description',
            field=models.TextField(max_length=150, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='rickrollpost',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
